apiVersion: v1
kind: Service
metadata:
  name: devops-poc-service
  labels:
    app: devops-poc-app
spec:
  type: LoadBalancer
  selector:
    app: devops-poc-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
