apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-poc-deploy
  namespace: devops-poc
spec:
  template:
    spec:
      containers:
      - name: devops-poc-web
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: devops-poc-docs
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"