apiVersion: v1
kind: Service
metadata:
  name: devops-poc-svc
  namespace: devops-poc
  labels:
    app: devops-poc-app
spec:
  type: LoadBalancer
  selector:
    app: devops-poc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: web
