apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-poc-deployment
  namespace: devops-poc-ns
spec:
  template:
    spec:
    containers:
      - name: devops-poc-web
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      - name: devops-poc-docs
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
